name: ci.yml
on:
  workflow_dispatch:
  push:
    branches:
      - releases/**
    paths:
      - .github/workflows/ci.yml
      - src
      - bun.lock
      - package.json
      - tsconfig.json
      - vite.config.ts

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.1
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '22'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest
      - name: Setup Vite
        run: npm install -g vite
      - name: Install dependencies
        run: bun install
      - name: Run package
        run: vite build && bun electrobun build --env=canary
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: linux-build-artifact
          path: | 
            build/canary-linux-x64/gugle-craft-launcher-canary/
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.1
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '22'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest
      - name: Setup Vite
        run: npm install -g vite
      - name: Install dependencies
        run: bun install
      - name: Run package
        run: vite build && bun electrobun build --env=canary
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: win-build-artifact
          path: |
            build/canary-win-x64/temp-bun-icon.ico
            build/canary-win-x64/temp-icon.ico
            build/canary-win-x64/temp-launcher-icon.ico
            build/canary-win-x64/gugle-craft-launcher-Setup-canary.tar.zst
            build/canary-win-x64/gugle-craft-launcher-Setup-canary.metadata.json
            build/canary-win-x64/gugle-craft-launcher-Setup-canary.exe
