name: ci.yml
on:
  workflow_dispatch:
  push:
    branches:
      - releases/**
    paths:
      - .github/workflows/ci.yml
      - src
      - bun.lock
      - package.json
      - tsconfig.json
      - vite.config.ts

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.1
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '22'
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
      - name: Install dependencies
        run: bun install
      - name: Run package
        run: vite build && electrobun build --env=canary
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: linux-build-artifact
          path: build/
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.1
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '22'
      - name: Install Bun
        run: powershell -c "irm bun.sh/install.ps1 | iex"
      - name: Install dependencies
        run: bun install
      - name: Run package
        run: vite build && electrobun build --env=canary
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: win-build-artifact
          path: build/
